### PR TITLE
Fix `fbs freeze` issue

### PR DESCRIPTION
**Pull request by X-sam**
adding a `__init__.py` to the root python dir works for `fbs run` but not `fbs freeze`- this PR fixes that oversight.

### CODE REVIEW

**Comment by dl1com** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=AllYarnsAreBeautiful_ayab-desktop&pullRequest=659) **Quality Gate failed**
> 
> Failed conditions  [E Reliability Rating on New Code](https://sonarcloud.io/dashboard?id=AllYarnsAreBeautiful_ayab-desktop&pullRequest=659) (required ≥ A)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=AllYarnsAreBeautiful_ayab-desktop&pullRequest=659)
> 
>  Catch issues before they fail your Quality Gate with our IDE extension  [SonarLint](https://www.sonarsource.com/products/sonarlint/features/connected-mode/?referrer=pull-request)

Can be ignored for this PR as caused by rearrangement of folders, therefore the whole codebase is treated as "new code" and this is exceeding the limit for additional issues for new code.

**Comment by X-sam** [comment]
> Can be ignored for this PR as caused by rearrangement of folders, therefore the whole codebase is treated as "new code" and this is exceeding the limit for additional issues for new code.

I did actually address some of its concerns in #660 so once I rebase this PR it should be less angry

**Comment by marygraceblair** [comment]
I checked out this branch and ran into this issue

image

Maybe it's just my machine? Or perhaps I'm just missing something, but I thought I should comment on it just in case.

**Comment by X-sam** [comment]
> I checked out this branch and ran into this issue
> 
> image
> Maybe it's just my machine? Or perhaps I'm just missing something, but I thought I should comment on it just in case.

You need to change the base config file locally- on ci builds it gets auto replaced with a version identifier. Most people don't use fbs freeze locally, so that's why it's not obvious!

**Comment by X-sam** [comment]
@marygraceblair did those instructions allow you to run it locally?

**Review by dl1com — APPROVED** [review]
LGTM, mostly moving files to please fbs freeze, plus adding an init action for github CI

**Pull request merged**
