### PR TITLE
Allow variable machine width (required to support KH270).

### PR DESCRIPTION
**Pull request by t0mpr1c3**
Referencing https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/133.

Relevant graphical methods and tests updated.

### CODE REVIEW

**Comment by t0mpr1c3** [comment]
I think I pushed the wrong version. It should work now, can you try again?

**Comment by chris007de** [comment]
> I think I pushed the wrong version. It should work now, can you try again?

Still not working. I think setting the KnitMode enum entries to `auto()` broke it. When changing it back to the static assignments, the program starts properly again.

Also:
- Closing the window does not quit the application properly, the log just shows `QXcbConnection: XCB error: 3 (BadWindow), sequence: 806, resource id: 10507589, major code: 40 (TranslateCoords), minor code: 0` and the application has to be closed with ctrl+c
- The combobox for languagues is empty in the preferences menu. I ran `setup_environment.sh` prior.

**Comment by t0mpr1c3** [comment]
OK, I'll try reinstalling my development environment. I'm a bit confused that I am not seeing the same errors.

**Comment by t0mpr1c3** [comment]
OK, I have fixed the language bug and the auto() bug. I can't replicated the problem on closing the window.

**Comment by chris007de** [comment]
> OK, I have fixed the language bug and the `auto()` bug. I have not replicated the problem on closing the window.

Ok, language and KnitMode is working for me now.
Exiting the application still fails, but let's handle this in another issue (in case it happens for somebody else than me, also)

**Pull request merged**
