### PR TITLE
Cache Ubuntu pip cache and results of setup-environment.sh

### PR DESCRIPTION
**Pull request by t0mpr1c3**
https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/460

### CODE REVIEW

**Comment by t0mpr1c3** [comment]
Release assets https://github.com/t0mpr1c3/ayab-desktop/releases/tag/untagged-228487dd648d7a850c21

**Comment by t0mpr1c3** [comment]
Release assets https://github.com/t0mpr1c3/ayab-desktop/releases/tag/test8d65116

**Comment by t0mpr1c3** [comment]
Release assets https://github.com/t0mpr1c3/ayab-desktop/releases/tag/untagged-cc121324ce3eb5b71038

**Comment by t0mpr1c3** [comment]
The proposed changes do not apply to the Windows build because the source files have different line endings and checksum.

**Comment by t0mpr1c3** [comment]
Release assets https://github.com/t0mpr1c3/ayab-desktop/releases/tag/untagged-f1fd23d7acef41582985

**Review by dl1com — APPROVED** [review]

**Pull request merged**
