### PR TITLE
Log current engine FSM state only on change

### PR DESCRIPTION
**Pull request by t0mpr1c3**
Addressing #537

### CODE REVIEW

**Comment by dl1com** [comment]
Still pollutes the log with 

```
2023-06-17 11:31:08,482 root     INFO     Notification: Initializing firmware
```

because it repeatedly returns the notification when in state INIT

https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/538/files#diff-14d2314eb34117bd0fd27de70bdfefca9735ba6a4cc85dff28dc10c5fccf2022R127

**Comment by t0mpr1c3** [comment]
I don't see output like that, but I pushed a new commit -- does that fix it?

**Comment by dl1com** [comment]
> I don't see output like that, but I pushed a new commit -- does that fix it?

That's probably caused by the unreliable serial communication I experience on my end.
But thanks for obfuscating the duplicate notifications, now the log looks nice and clear.

**Review by dl1com — APPROVED** [review]

**Comment by dl1com** [comment]
Just as a note:
while-looping within the states causes that the UI is non-responsive while being inside that loop. So i.e. waiting for a indState in _API6_request_start renders the cancel button useless.
We should fix that timely.

**Comment by t0mpr1c3** [comment]
That shouldn't happen because the GUI and the engine are in separate threads.

**Pull request merged**
